language: node_js

node_js:
- '8'
- '7'
- '6'
- '5'
- '4'

matrix:
  fast_finish: true

env:
- MONGODB_HOST=127.0.0.1:27017 MYSQL_HOST=127.0.0.1:3306
  POSTGRES_HOST=127.0.0.1:5432 RABBITMQ_HOST=127.0.0.1:5672
  REDIS_HOST=127.0.0.1:6379

services:
- docker
- mongodb
- mysql
- postgresql
- rabbitmq
- riak
- redis

sudo: required

before_install:
- docker --version

script:
- npm install -g json
- npm run ci

deploy:
  provider: npm
  email: simon@simonemms.com
  api_key:
    secure: xuqd1LDwykLACeazIxsjTs5Ir9d0lVpDaDSlooeRo3WlqU2uH60Uf+GpC+ERYOyEIbrbS1ya6NEYnI30zhRKeYR9ehmvtue95OGY4sysOwT2NrmzXdW0sb7JLwqR9omJO2Ow5rSHwg6X6fm/By0O6WSLIH9Fj6ysbnX8d+9uxKbgawUFcSRYzEW6UCy0TkogqXK6zupQmBzoXkYsUOIiS7GLRtOplWi7xS2T1odPgBuMwRbG5pI7ZCB3mumhGlY6BiE0pvxjpPIw0sSJyVyYIazBeON+eULFqwMOKbJcCNDoBaMO5qqpv1s08lSa9bmSzWfLjCh7NvgdumDXPf0X8bxzoeonBSDL/emXdlzAERfbAryeLC2GHoYNL5sUmGhZgrzxiEZxbu0TTpVR4y6NniKV/kbs5Xzddh0fWe9pWqZhGYWgu5fZkjC9UvVpSUWPh/a4HRDdE3gllkXB7dCGswNa/ShBdzR0N5EgkH9ywZd3RsgeQ25BRaKYsnTA9OxENCVy3QhcF/9WJfZaMW/D/jhi/ZIr0/1CrGbIy8Hz8QIInZN0yJRDhUATzFKiN0x3HlMOIQ2rTWv8fN2oMK5XKF/iy4pjg2eCleBwxG+B9Eb7JR4XiuSBaz0tebXxpEaLY6sLQm/qz58Eza5rfv51uaa2+MZoSZZF8K29CkeA1IA=
  on:
    all_branches: true
    tags: true
    repo: riggerthegeek/is_ready

after_deploy:
- sh ./trigger_docker.sh
