language: node_js

node_js:
- '8'
- '7'
- '6'
- '5'
- '4'

matrix:
  fast_finish: true

env:
- MONGODB_HOST=127.0.0.1:27017 MYSQL_HOST=127.0.0.1:3306 POSTGRES_HOST=127.0.0.1:5432
  RABBITMQ_HOST=127.0.0.1:5672 REDIS_HOST=127.0.0.1:6379

services:
- docker
- mongodb
- mysql
- postgresql
- rabbitmq
- riak
- redis

sudo: required

before_install:
- docker --version

script:
- npm install -g json
- npm run ci

deploy:
  provider: npm
  email: simon@simonemms.com
  api_key:
    secure: IIUwxVHRORPnJYT3OI7uiCNEvbgQByry4LvzA1OqM81sv7NcEwJwxiwk0EddJfOkO/7MJw+LIKZAHliCyCTzVWg+Pl8qo99gcySO3mOmDX5iJVRawYUkTvWv6LMoEU/JaS6wOufcRQIwEVG2+/7veuJMhkM615rgPhFmdknL3zPanDDpUK5ZAdtxB41PrPr+9InG4SU2AKy6S7WgBfYcsDQmkgXLNPsbLU6Uo4FrLbC7SXb9pZi3VnbMF6o12aBRpJtvmcnF9IwEEaSPJDjqALgpEZ8buT6uVaexYgHbsQFhkd2BjHkALGTVxtR9uOSCIH1r3AzRFTggN5VRDou6TjVf5pMUIEzv1n4L7sBNFYIZpmpBLzLZPBmwHAIL87FHoNSAjcBP2faZXfloam+At3mU1RffaEsiUHb6GpINa2m455T82ngyAZXjVr/8WNdzXVUbTteiNjisEbAdsUqMzSxeaFwbpXqJBk6iqnxnRuz09m4zJ5hodN4gu8UaFnmTCpX2CtLAeB/3bkZ1L/zreu7bUUgbBxqVsE/8Y8QHaZ/F3/dez01FpOoLxbIF4vvQFrJ2NwePMlpihxfZOhr0AIUTPjVlKyRS+gdPTY6oapk1I9Px1FXUlae3IOrG09BSnqooX+rYpXq2+MJNKwtaSPzZ2WNVCxhh7eCJ4yIj/Os=
  on:
    all_branches: true
    tags: true
    repo: riggerthegeek/is_ready

after_deploy:
- sh ./trigger_docker.sh
