version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - .:/opt/is_ready
    environment:
      - MONGODB_HOST=mongodb:27017
      - MYSQL_HOST=mysql:3306
      - POSTGRES_HOST=postgresql:5432
      - RABBITMQ_HOST=rabbitmq:5672
      - REDIS_HOST=redis:6379
    links:
      - mongodb
      - mysql
      - postgresql
      - rabbitmq
      - redis

  mongodb:
    image: mongo

  mysql:
    image: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1

  postgresql:
    image: postgres

  rabbitmq:
    image: rabbitmq

  redis:
    image: redis
